services:
  mongodb:
    image: mongo:latest
    container_name: filezify-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - filezify-network

volumes:
  mongodb_data:

networks:
  filezify-network:
    driver: bridge 