version: "3.8"

services:
  # Config servers (replica set for configsvr)
  configsvr1:
    image: mongo:latest
    container_name: configsvr1
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27017", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - configsvr1_data:/data/db

  configsvr2:
    image: mongo:latest
    container_name: configsvr2
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27017", "--bind_ip_all"]
    volumes:
      - configsvr2_data:/data/db

  configsvr3:
    image: mongo:latest
    container_name: configsvr3
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27017", "--bind_ip_all"]
    volumes:
      - configsvr3_data:/data/db

  # mongos router
  mongos:
    image: mongo:latest
    container_name: mongos
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
    command: >
      mongos --configdb configReplSet/configsvr1:27017,configsvr2:27017,configsvr3:27017 --bind_ip_all
    ports:
      - "27017:27017"

  # Shard 1 (3-node replica set)
  shard1-node1:
    image: mongo:latest
    container_name: shard1-node1
    command: ["mongod", "--shardsvr", "--replSet", "shard1", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard1_node1_data:/data/db

  shard1-node2:
    image: mongo:latest
    container_name: shard1-node2
    command: ["mongod", "--shardsvr", "--replSet", "shard1", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard1_node2_data:/data/db

  shard1-node3:
    image: mongo:latest
    container_name: shard1-node3
    command: ["mongod", "--shardsvr", "--replSet", "shard1", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard1_node3_data:/data/db

  # Shard 2 (3-node replica set)
  shard2-node1:
    image: mongo:latest
    container_name: shard2-node1
    command: ["mongod", "--shardsvr", "--replSet", "shard2", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard2_node1_data:/data/db

  shard2-node2:
    image: mongo:latest
    container_name: shard2-node2
    command: ["mongod", "--shardsvr", "--replSet", "shard2", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard2_node2_data:/data/db

  shard2-node3:
    image: mongo:latest
    container_name: shard2-node3
    command: ["mongod", "--shardsvr", "--replSet", "shard2", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard2_node3_data:/data/db

  # Shard 3 (3-node replica set)
  shard3-node1:
    image: mongo:latest
    container_name: shard3-node1
    command: ["mongod", "--shardsvr", "--replSet", "shard3", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard3_node1_data:/data/db

  shard3-node2:
    image: mongo:latest
    container_name: shard3-node2
    command: ["mongod", "--shardsvr", "--replSet", "shard3", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard3_node2_data:/data/db

  shard3-node3:
    image: mongo:latest
    container_name: shard3-node3
    command: ["mongod", "--shardsvr", "--replSet", "shard3", "--port", "27017", "--bind_ip_all"]
    volumes:
      - shard3_node3_data:/data/db

volumes:
  configsvr1_data:
  configsvr2_data:
  configsvr3_data:
  shard1_node1_data:
  shard1_node2_data:
  shard1_node3_data:
  shard2_node1_data:
  shard2_node2_data:
  shard2_node3_data:
  shard3_node1_data:
  shard3_node2_data:
  shard3_node3_data:
